### ISSUE TITLE
We need ETB

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen88bmw-issues#1]
That ETB which we have removed?

@stefanst says we need it

6 pin JST for pedal pigtail connector
    two position sensors - analog inputs same as pedal on Nissan121 or vag 121
    two GND
    two 5v

4 pin JST for low current of TPS pigtail connector
    two position sensors - analog inputs same as TPS on Nissan121 or vag 121. one of these sensors also wired into 88 pin if this car has potentiometer TPS
  single GND, single 5v

Molex MiniFit Jr. 2-pin connector for DC motor

@stefanst do we have pins to reuse? if not how do you see it?

**Comment by rusefillc** [comment]
@ivanchuba please show me "6 pin JST" on the PCB

same "Molex MiniFit Jr. 2-pin connector for DC motor"

**Comment by ivanchuba** [comment]
![image](https://user-images.githubusercontent.com/2463786/129451296-6fefcbe8-0b66-464b-b6a6-db9b2c8427d9.png)

**Comment by ivanchuba** [comment]
![image](https://user-images.githubusercontent.com/2463786/129451366-6ca3fb43-73f4-43f0-a554-b795c4c20fa5.png)

**Comment by rusefillc** [comment]
are those 2.54 headers or JST with JLC part numbers?

do we need to improve silkscreen of those?

**Comment by ivanchuba** [comment]
2.54 headers 
silkscreen for PINs is a bottom side

**Comment by rusefillc** [comment]
We really need those to be JST connectors with JLC part numbers

if we are badly out of space first thing to be removed would be "GND" P1 of WBO - that way we can shift all other holes and get space?

![image](https://user-images.githubusercontent.com/48498823/129520364-d497cc3e-4707-4c89-8f26-7956540a15e2.png)

**Comment by ivanchuba** [comment]
there was enough space

**Comment by ivanchuba** [comment]
@rusefillc please check ETB connection

**Comment by ivanchuba** [comment]
@rusefillc  please check

**Comment by rusefillc** [comment]
Good enough for now
