### ISSUE TITLE
Pin 48 - AC compressor (Currently NC) 

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/hellen88bmw-issues#12]
We can control AC so we should connect this.

**Comment by andreika-git** [comment]
@OrchardPerformance OUT_LOW4_DUAL (max.current 1A) would be enough? They use 5A fuse for that relay...
![image](https://user-images.githubusercontent.com/15104768/130027947-b91a8531-3842-4b22-986d-81ea9051fc42.png)

**Comment by rusefillc** [comment]
let's have a jumper and OUT_LOW4_DUAL and try this

**Comment by ivanchuba** [comment]
done
