### ISSUE TITLE
MAIN_RELAY is totally *ed up!

### ISSUE THREAD

**Issue by andreika-git** [rusefi/hellen88bmw-issues#16]
![image](https://user-images.githubusercontent.com/15104768/130009546-c2ad2497-c6b0-4d74-9fcd-7d602a1ab2c8.png)
![image](https://user-images.githubusercontent.com/15104768/130009594-90a9d1b6-1e53-4da8-a68b-a5bd1ab18b59.png)
![image](https://user-images.githubusercontent.com/15104768/130009642-7ec12ab3-cc29-4815-8858-1891de3ff04c.png)
![image](https://user-images.githubusercontent.com/15104768/130009685-5fd886cd-0e7b-4041-9eff-1a6b9dadac9e.png)

**Comment by rusefillc** [comment]
@ivanchuba please elaborate on what went wrong here. We've touched this area twice already, where is the misunderstanding happening - is the problem with the wiring diagram? is the problem with naming on the modules? else?

**Comment by rusefillc** [comment]
Подключение главного реле перепутано напрочь:
- "MAIN_RELAY" и "OUT_MAIN" поменялись местами
- выходы на главное реле замыкаются на входы
- почему-то подключаются к шинам зажигания и инжекторов, что ещё больше запутывает

Как должно быть сделано правильно:
- выход модуля mcu OUT_IO1 - это MAIN_RELAY
- MAIN_RELAY идёт на LOW5_MAIN модуля output
- выход OUT_LOW5_MAIN модуля output - это OUT_MAIN
- OUT_MAIN идёт на пин 27 коннектора через джампер

**Comment by ivanchuba** [comment]
done
