### ISSUE TITLE
CLT/IAT are *ed up

### ISSUE THREAD

**Issue by andreika-git** [rusefi/hellen88bmw-issues#17]
![image](https://user-images.githubusercontent.com/15104768/130010752-c4ae13c3-22d6-4364-9cc3-fd82a44f0077.png)

**Comment by rusefillc** [comment]
@ivanchuba this is very sad :(

**Comment by rusefillc** [comment]
Цепи от коннектора до входа модуля input должны быть IN_CLT и IN_IAT, а цепи с выхода модуля input на вход модуля mcu должны быть CLT и IAT. Это разные цепи. А сейчас входы и выходы просто накоротко замкнуты между собой - это не очень красиво получается, если честно...

**Comment by ivanchuba** [comment]
done
