### ISSUE TITLE
Solenoid flyback diodes? Idle solenoid?

### ISSUE THREAD

**Issue by andreika-git** [rusefi/hellen88bmw-issues#18]
Do we have at least one solenoid in this car? Maybe the idle valve?
Then we need flyback diodes for them like on the other boards:
![image](https://user-images.githubusercontent.com/15104768/130011621-b6273f7e-dd18-4d6f-acce-972b8596a71f.png)
Currently I don't see any of those on the board.

**Comment by andreika-git** [comment]
Maybe we should also use a separate power MOSFET for idle actuator as in HellenNB2?

**Comment by rusefillc** [comment]
@andreika-git do we have documentation for current limits of 

![image](https://user-images.githubusercontent.com/48498823/130066319-6e779fd3-e5b0-4d5e-a691-fdbff7c4538f.png)

Shall we rename OUT_LOW1 to OUT_LOW1_RELAY or OUT_LOW1_LOGIC or OUT_LOW1_LOW_CURRENT or something to make it more self-documenting?

**Comment by andreika-git** [comment]
https://github.com/andreika-git/hellen-one/wiki/module-output

**Comment by ivanchuba** [comment]
done, please check

**Comment by rusefillc** [comment]
Давай поставим наши любимые B5819W (C8598) 1A rated?

**Comment by rusefillc** [comment]
B5819W and  separate power MOSFET like https://github.com/rusefi/rusefi/wiki/Hardware/Hellen/hellen72-d-schematic.pdf same as on injector output channels just manual schematics

**Comment by ivanchuba** [comment]
![image](https://user-images.githubusercontent.com/2463786/131534903-6c38b591-73ae-4bdb-b0f2-9188f919295b.png)
done

**Comment by rusefillc** [comment]
@Qwerty-OFF can we close this one?

**Comment by Qwerty-OFF** [comment]
Yes, we have good diodes for IDLE (2 wires), VVT and I don’t know why for EVAP
