### ISSUE TITLE
ETB capacitors voltage rating

### ISSUE THREAD

**Issue by andreika-git** [rusefi/hellen88bmw-issues#21]
0603-6.3V capacitors are not enough for 12V rail. We should use at least 0805-25V capacitors (C15850)
![image](https://user-images.githubusercontent.com/15104768/131620344-26db49cb-f44d-4c6a-b557-6576455c6197.png)
![image](https://user-images.githubusercontent.com/15104768/131620355-9599a4ec-513d-4315-8671-738d22da4493.png)

**Comment by rusefillc** [comment]
@ivanchuba please confirm that H-bridge schematics matches hellen121vag exactly

**Comment by Qwerty-OFF** [comment]
Currently in use C96446
![image](https://user-images.githubusercontent.com/4116383/133508672-1dc15fed-7a85-4b16-a9fc-ceefeaffc158.png)

**Comment by rusefillc** [comment]
@Qwerty-OFF can we close this one?

**Comment by Qwerty-OFF** [comment]
Yes
