### ISSUE TITLE
high voltage track gaps

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen88bmw-issues#22]
@Qwerty-OFF what is the official track gap we have settled on for coil drivers on https://github.com/rusefi/hellen128mercedes ?

@ivanchuba track gaps would have to be wider since we design for XXX voltage (200? 300? 500?)

**Comment by Qwerty-OFF** [comment]
0.8mm for coated tracks, 0.25mm for inner layers and 2.5mm between high voltage and other pads
![image](https://user-images.githubusercontent.com/4116383/132106844-70d17867-bd7d-4ced-b07a-53acf4f773f8.png)

**Comment by rusefillc** [comment]
This is now https://github.com/andreika-git/hellen-one/wiki/Dumb-Coils-Igniters

**Comment by Qwerty-OFF** [comment]
Already done in rev. a
