### ISSUE TITLE
Replace BOOT0 silk with PROG

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen88bmw-issues#26]
![image](https://user-images.githubusercontent.com/48498823/138164586-35ed8510-f35a-4e7a-9b66-6bb22c9eb19a.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/174470005-731451db-9ee1-48e7-af81-738caa81bcec.png)
