### ISSUE TITLE
Pin 8 - Check engine light (currently NC)

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/hellen88bmw-issues#3]
We should connect the check engine light as the software will use the light in future to warn of errors. (it is in the smart ECU plans).

**Comment by andreika-git** [comment]
@OrchardPerformance Is CE lamp lowside-active or highside-active?

**Comment by rusefillc** [comment]
@ivanchuba please add a via for now #20

**Comment by ivanchuba** [comment]
> @OrchardPerformance Is CE lamp lowside-active or highside-active?

@OrchardPerformance not have answer?

**Comment by OrchardPerformance** [comment]
Will try to check when its daylight tomorrow

**Comment by ivanchuba** [comment]
@OrchardPerformance ok, thanks

**Comment by Qwerty-OFF** [comment]
@OrchardPerformance Did you check how to connect the lamp?

**Comment by rusefillc** [comment]
@Qwerty-OFF do we have at least a via?

**Comment by Qwerty-OFF** [comment]
Via in rev. a
Connected now:
![image](https://user-images.githubusercontent.com/4116383/174687021-c4b4e593-e269-4d7d-9223-f8d7d510bd82.png)
