### ISSUE TITLE
Fuses too close to IGBTs for hand soldering

### ISSUE THREAD

**Issue by stefanst** [rusefi/hellen88bmw-issues#33]
![image](https://user-images.githubusercontent.com/709317/138540766-15fc0214-16e8-4797-ae3d-042d575ce6d6.png)
Possible solutions:
- Have fuses as DNP and hand-solder after IGBTs have been added
- Move fuses to a more convenient location

**Comment by rusefillc** [comment]
* move R23 and shift IGBTs away from fuses?

* rotate fuses and have R14 between fuse and IGBT?

**Comment by rusefillc** [comment]
* move R14 to back side of PCB?

**Comment by stefanst** [comment]
R14 is not really the issue as far as I can see.
The IGBTs need some pad area for cooling. The more the better. That would be made more difficult if they got turned.

Somewhat related question: Why are R14 et al so big? Looks like they're just for logic-level switching.

**Comment by rusefillc** [comment]
We do not want spark to jump R14 gap. It's about open air distance when we play dumb coils

Not turning IGBTs but turning fuses, with R14 between fuse and IGBT

**Comment by stefanst** [comment]
That makes sense!

**Comment by Qwerty-OFF** [comment]
IGBT moved left 2mm
![image](https://user-images.githubusercontent.com/4116383/174688447-49918492-00fa-46a4-b6ff-2055ef3dd9da.png)
