### ISSUE TITLE
All DNP jumpers are populated

### ISSUE THREAD

**Issue by stefanst** [rusefi/hellen88bmw-issues#34]
JP6, JP 20, JP 21, JP 41 and JP 56 should be DNP as per the schematic. They are, in fact, populated though.
![image](https://user-images.githubusercontent.com/709317/139514968-54a77785-ed0a-4091-bbb8-10ebd91fb40f.png)
![image](https://user-images.githubusercontent.com/709317/139515001-5a8e475b-51f8-4819-99e8-a7a2f31f12f7.png)
![image](https://user-images.githubusercontent.com/709317/139515030-fb637d4b-daa5-4545-b23a-1d800dc82569.png)
![image](https://user-images.githubusercontent.com/709317/139515050-0f129392-c98d-4f2a-af73-afb9b8f3e14c.png)

**Comment by rusefillc** [comment]
https://github.com/andreika-git/hellen-one/issues/78

**Comment by Qwerty-OFF** [comment]
Fixed
