### ISSUE TITLE
TS: MAP pin can't be selected for MAP input

### ISSUE THREAD

**Issue by stefanst** [rusefi/hellen88bmw-issues#42]

**Comment by rusefillc** [comment]
@stefanst you should use "Aux MAP" - it's there since yesterday

![image](https://user-images.githubusercontent.com/48498823/141223269-6e7db5e6-b019-4580-8438-3fec97f6053a.png)

**Comment by stefanst** [comment]
It was not available in my 3 day-old FW/INI. It IS available with the latest.
