### ISSUE TITLE
Narrowband O2 sensor(s) not connected on board

### ISSUE THREAD

**Issue by stefanst** [rusefi/hellen88bmw-issues#43]
Pin 13 should be the signal for the NBO2 sensor on the M3.3.1 (m50). It seems to be disconnected. Pin 12 should also be an NBO2 signal on additional engines. It also seems to be disconnected.

**Comment by rusefillc** [comment]
we need just vias for now

**Comment by Qwerty-OFF** [comment]
Already in rev. a
