### ISSUE TITLE
Schematics usability: make ETB stuff a bit more visible

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen88bmw-issues#47]
We need a a blue comment next to J19 articulating that it's "drive-by-wire motor connector"

Also add explicit "Electronic Throttle Body/ETB where it says just ETB in the top-right corner of my snippet

![image](https://user-images.githubusercontent.com/48498823/154555958-8f543f1c-51ea-4b44-8017-ffdcf478baaf.png)

**Comment by Qwerty-OFF** [comment]
![image](https://user-images.githubusercontent.com/4116383/174470248-1cf0c90d-0905-4424-8063-ce1879df49e0.png)
