### ISSUE TITLE
osc part number

### ISSUE THREAD

**Issue by rusefillc** [rusefi/hellen88bmw-issues#7]
![image](https://user-images.githubusercontent.com/48498823/129846971-cd767ffa-1cbd-490e-94b3-9cd957b4b8ea.png)

I found the reason should be there is no price for the part #:C112566.

need a PN with price

**Comment by andreika-git** [comment]
![image](https://user-images.githubusercontent.com/15104768/129950300-9fe6e727-c9d4-40d3-8c0d-e1134f1e1c84.png)

**Comment by rusefillc** [comment]
JLC has resolved on their end
