### ISSUE TITLE
Pin 36 - EVAP valve (Currently NC) 

### ISSUE THREAD

**Issue by OrchardPerformance** [rusefi/hellen88bmw-issues#8]
We should connect the evap valve to a low side so it can be operated via GPIO, it is part of the PCV system on the M5x engine

**Comment by andreika-git** [comment]
Let's use OUT_LOW3_DUAL + flyback diode

**Comment by OrchardPerformance** [comment]
I will check the ohms of the valve (its hanging loose in my e30) your suggestion will probably be OK.

**Comment by rusefillc** [comment]
нужно сделать (OUT_LOW3_DUAL+diode), плюс не забыть соединить LOW3_DUAL с OUT_IOx у mcu

**Comment by ivanchuba** [comment]
done
